apiVersion: getambassador.io/v3alpha1
kind: Host
metadata:
  name: wildcard-host
spec:
  hostname: "*"
  acmeProvider:
    authority: none
  tlsSecret:
    name: emissary-tls-cert
  selector:
    matchLabels:
      hostname: wildcard-host